// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: admin/login.proto

package admin

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	unified "github.com/ops-cn/go-devops/proto/unified"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Login service

func NewLoginEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Login service

type LoginService interface {
	//  rpc GetCaptcha (Length) returns(unified.Response) {}
	//  rpc ResCaptcha (LoginCaptcha) returns(unified.Response) {}
	Verify(ctx context.Context, in *LoginParam, opts ...client.CallOption) (*unified.Response, error)
}

type loginService struct {
	c    client.Client
	name string
}

func NewLoginService(name string, c client.Client) LoginService {
	return &loginService{
		c:    c,
		name: name,
	}
}

func (c *loginService) Verify(ctx context.Context, in *LoginParam, opts ...client.CallOption) (*unified.Response, error) {
	req := c.c.NewRequest(c.name, "Login.Verify", in)
	out := new(unified.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Login service

type LoginHandler interface {
	//  rpc GetCaptcha (Length) returns(unified.Response) {}
	//  rpc ResCaptcha (LoginCaptcha) returns(unified.Response) {}
	Verify(context.Context, *LoginParam, *unified.Response) error
}

func RegisterLoginHandler(s server.Server, hdlr LoginHandler, opts ...server.HandlerOption) error {
	type login interface {
		Verify(ctx context.Context, in *LoginParam, out *unified.Response) error
	}
	type Login struct {
		login
	}
	h := &loginHandler{hdlr}
	return s.Handle(s.NewHandler(&Login{h}, opts...))
}

type loginHandler struct {
	LoginHandler
}

func (h *loginHandler) Verify(ctx context.Context, in *LoginParam, out *unified.Response) error {
	return h.LoginHandler.Verify(ctx, in, out)
}
