// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package injector

import (
	"github.com/ops-cn/go-devops/admin/app/bll/impl/bll"
	"github.com/ops-cn/go-devops/admin/app/model/impl/gorm/model"
)

// Injectors from wire.go:

func BuildInjector() (*Injector, func(), error) {
	db, cleanup, err := InitGormDB()
	if err != nil {
		return nil, nil, err
	}
	trans := &model.Trans{
		DB: db,
	}
	menu := &model.Menu{
		DB: db,
	}
	menuAction := &model.MenuAction{
		DB: db,
	}
	menuActionResource := &model.MenuActionResource{
		DB: db,
	}
	bllMenu := &bll.Menu{
		TransModel:              trans,
		MenuModel:               menu,
		MenuActionModel:         menuAction,
		MenuActionResourceModel: menuActionResource,
	}
	injector := &Injector{
		MenuBll: bllMenu,
	}
	return injector, func() {
		cleanup()
	}, nil
}
